# Netlify configuration for Keyboard Tester
[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_OPTIONAL = "true"
